version: "3.3"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_bi:/var/lib/postgresql/data
    env_file:
      - .env_example
    ports:
      - 5000:5000
  web:
    container_name: django_blog_api
    build:
      context: ../
      dockerfile: docker/Dockerfile
    tty: true
    command: docker/start.sh
    ports:
      - "8000:8000"
    env_file:
      - .env_example
    depends_on:
      - db

volumes:
  postgres_bi: